const PLACEHOLDER_IMAGE = "images/PLACEHOLDER_IMAGE.png";

export const cars = [
    {
        name: "Audi A6",
        type: "audi",
        price: 55000,
        engine: "V6",
        topSpeed: 250,
        fuel: "Petrol",
        seats: 5,
        images: [
            "images/audi a6/Audi A6.jpg",
            "images/audi a6/Audi A6_2.jpg",
            "images/audi a6/Audi A6_3.jpg",
            "images/audi a6/Audi A6_4.jpg",
        ],
        specs: "V6 engine, 335 HP, 8-speed automatic",
        description: "Luxury sedan with smooth ride, advanced tech, and strong V6 performance.",
    },
    {
        name: "Audi Q5",
        type: "audi",
        price: 60000,
        engine: "V6",
        topSpeed: 240,
        fuel: "Petrol",
        seats: 5,
        images: ["images/Audi Q5/Audi Q5.jpg", "images/Audi Q5/Audi Q5_4.jpg"],
        specs: "V6 engine, 349 HP, 7-speed automatic",
        description: "Compact luxury SUV with balanced performance, comfort, and practicality.",
    },
    {
        name: "Audi A8",
        type: "audi",
        price: 90000,
        engine: "V8",
        topSpeed: 250,
        fuel: "Petrol",
        seats: 5,
        images: ["images/Audi A8/Audi A8.jpg", "images/Audi A8/Audi A8_4.jpg"],
        specs: "V8 engine, 453 HP, 8-speed automatic",
        description: "Flagship sedan offering premium comfort, cutting-edge tech, and quiet power.",
    },

    {
        name: "Tesla Model S",
        type: "tesla",
        price: 80000,
        engine: "Electric",
        topSpeed: 322,
        fuel: "Electric",
        seats: 5,
        images: [
            "images/Tesla Model S/Tesla Model S.jpg",
            "images/Tesla Model S/Tesla Model S_2.jpg",
            "images/Tesla Model S/Tesla Model S_3.jpg",
            "images/Tesla Model S/Tesla Model S_4.jpg",
        ],
        specs: "Electric, 670 HP, 405 miles range",
        description: "High-end electric sedan with extreme acceleration and long range.",
    },
    {
        name: "Tesla Model 3",
        type: "tesla",
        price: 40000,
        engine: "Electric",
        topSpeed: 261,
        fuel: "Electric",
        seats: 5,
        images: [
            "images/Tesla Model 3/Tesla Model 3.jpg",
            "images/Tesla Model 3/Tesla Model 3_2.jpg",
            "images/Tesla Model 3/Tesla Model 3_4.jpg",
        ],
        specs: "Electric, 283 HP, 358 miles range",
        description: "Affordable electric sedan with minimalist design and efficient performance.",
    },
    {
        name: "Tesla Model X",
        type: "tesla",
        price: 90000,
        engine: "Electric",
        topSpeed: 262,
        fuel: "Electric",
        seats: 7,
        images: [
            "images/Tesla Model X/Tesla Model X.jpg",
            "images/Tesla Model X/Tesla Model X_2.jpg",
            "images/Tesla Model X/Tesla Model X_4.jpg",
        ],
        specs: "Electric, 670 HP, 348 miles range",
        description: "Luxury electric SUV with falcon-wing doors and strong performance.",
    },

    {
        name: "Mercedes-Benz S-Class",
        type: "mercedes",
        price: 110000,
        engine: "V8",
        topSpeed: 250,
        fuel: "Petrol",
        seats: 5,
        images: [
            "images/Mercedes-Benz S-Class/Mercedes-Benz S-Class.jpg",
            "images/Mercedes-Benz S-Class/Mercedes-Benz S-Class_2.jpg",
            "images/Mercedes-Benz S-Class/Mercedes-Benz S-Class_3.jpg",
            "images/Mercedes-Benz S-Class/Mercedes-Benz S-Class_4.jpg",
        ],
        specs: "V8 engine, 496 HP, 9-speed automatic",
        description: "Ultimate luxury sedan with unmatched comfort, technology, and prestige.",
    },
    {
        name: "Mercedes-Benz E-Class",
        type: "mercedes",
        price: 70000,
        engine: "V6",
        topSpeed: 250,
        fuel: "Petrol",
        seats: 5,
        images: [
            "images/Mercedes-Benz E-Class/Mercedes-Benz E-Class.jpg",
            "images/Mercedes-Benz E-Class/Mercedes-Benz E-Class_3.jpg",
            "images/Mercedes-Benz E-Class/Mercedes-Benz E-Class_4.jpg",
        ],
        specs: "V6 engine, 362 HP, 9-speed automatic",
        description: "Executive sedan blending luxury, performance, and everyday usability.",
    },
    {
        name: "Mercedes-Benz GLE",
        type: "mercedes",
        price: 80000,
        engine: "V6",
        topSpeed: 250,
        fuel: "Petrol",
        seats: 5,
        images: [
            "images/Mercedes-Benz GLE/Mercedes-Benz GLE.jpg",
            "images/Mercedes-Benz GLE/Mercedes-Benz GLE_2.jpg",
            "images/Mercedes-Benz GLE/Mercedes-Benz GLE_3.jpg",
            "images/Mercedes-Benz GLE/Mercedes-Benz GLE_4.jpg",
        ],
        specs: "V6 engine, 362 HP, 9-speed automatic",
        description: "Mid-size luxury SUV with smooth ride, advanced features, and comfort.",
    },

    {
        name: "Porsche 911",
        type: "porsche",
        price: 120000,
        engine: "Flat-6",
        topSpeed: 330,
        fuel: "Petrol",
        seats: 2,
        images: [
            "images/Porsche 911/Porsche 911.jpg",
            "images/Porsche 911/Porsche 911_2.jpg",
            "images/Porsche 911/Porsche 911_3.jpg",
            "images/Porsche 911/Porsche 911_4.jpg",
        ],
        specs: "Flat-6 engine, 379 HP, 8-speed PDK",
        description: "Iconic sports car delivering precision handling and timeless design.",
    },
    {
        name: "Porsche Cayenne",
        type: "porsche",
        price: 90000,
        engine: "V8",
        topSpeed: 286,
        fuel: "Petrol",
        seats: 5,
        images: [
            "images/Porsche Cayenne/Porsche Cayenne.jpg",
            "images/Porsche Cayenne/Porsche Cayenne_2.jpg",
            "images/Porsche Cayenne/Porsche Cayenne_3.jpg",
            "images/Porsche Cayenne/Porsche Cayenne_4.jpg",
        ],
        specs: "V8 engine, 453 HP, 8-speed automatic",
        description: "Performance SUV combining Porsche dynamics with daily usability.",
    },
    {
        name: "Porsche Taycan",
        type: "porsche",
        price: 100000,
        engine: "Electric",
        topSpeed: 260,
        fuel: "Electric",
        seats: 4,
        images: [
            "images/Porsche Taycan/Porsche Taycan.jpg",
            "images/Porsche Taycan/Porsche Taycan_2.jpg",
            "images/Porsche Taycan/Porsche Taycan_3.jpg",
            "images/Porsche Taycan/Porsche Taycan_4.jpg",
        ],
        specs: "Electric, 616 HP, AWD",
        description: "High-performance electric sedan with Porsche driving DNA.",
    },

    {
        name: "Lamborghini Huracan",
        type: "lamborghini",
        price: 250000,
        engine: "V10",
        topSpeed: 325,
        fuel: "Petrol",
        seats: 2,
        images: [
            "images/Lamborghini Huracan/Lamborghini Huracan.jpg",
            "images/Lamborghini Huracan/Lamborghini Huracan_2.jpg",
            "images/Lamborghini Huracan/Lamborghini Huracan_3.jpg",
            "images/Lamborghini Huracan/Lamborghini Huracan_4.jpg",
        ],
        specs: "V10 engine, 610 HP, 7-speed dual-clutch",
        description: "Exotic supercar with extreme speed, sharp handling, and iconic design.",
    },
    {
        name: "Ferrari F8 Tributo",
        type: "ferrari",
        price: 280000,
        engine: "V8 Twin-Turbo",
        topSpeed: 340,
        fuel: "Petrol",
        seats: 2,
        images: [PLACEHOLDER_IMAGE],
        specs: "Twin-turbo V8, 710 HP, 7-speed dual-clutch",
        description: "Ferrari supercar delivering breathtaking performance and precision.",
    },

    {
        name: "Toyota Land Cruiser",
        type: "toyota",
        price: 70000,
        engine: "V6 Twin-Turbo",
        topSpeed: 210,
        fuel: "Petrol",
        seats: 7,
        images: [PLACEHOLDER_IMAGE],
        specs: "Twin-turbo V6, 409 HP, 10-speed automatic",
        description: "Legendary SUV known for durability, off-road power, and reliability.",
    },
    {
        name: "Toyota Corolla",
        type: "toyota",
        price: 25000,
        engine: "I4",
        topSpeed: 180,
        fuel: "Petrol",
        seats: 5,
        images: [PLACEHOLDER_IMAGE],
        specs: "Inline-4 engine, 169 HP, CVT",
        description: "Reliable and efficient daily car with low fuel consumption.",
    },

    {
        name: "Ford Mustang GT",
        type: "ford",
        price: 55000,
        engine: "V8",
        topSpeed: 250,
        fuel: "Petrol",
        seats: 4,
        images: [PLACEHOLDER_IMAGE],
        specs: "V8 engine, 450 HP, 6-speed manual / 10-speed auto",
        description: "Classic American muscle car with powerful V8 and aggressive sound.",
    },
    {
        name: "Chevrolet Camaro",
        type: "chevrolet",
        price: 50000,
        engine: "V8",
        topSpeed: 250,
        fuel: "Petrol",
        seats: 4,
        images: [PLACEHOLDER_IMAGE],
        specs: "V8 engine, 455 HP, 6-speed manual / 10-speed auto",
        description: "Muscle coupe combining bold design with strong straight-line performance.",
    },
].map((car) => {
    const images = Array.isArray(car.images) && car.images.length ? car.images : [PLACEHOLDER_IMAGE];
    return { ...car, images, image: images[0] };
});

export const logos=cars.map(car => {
    const type= car.type;
    const images = {
        audi: "images/logos/audi.png",
        tesla: "images/logos/tesla.png",
        mercedes: "images/logos/mercedes.png",
        bmw: "images/logos/bmw.png",
        porsche: "images/logos/porsche.png",
        lamborghini: "images/logos/lamborghini.png",
        ferrari: "images/logos/ferrari.png",
        toyota: "images/logos/toyota.png",
        ford: "images/logos/ford.png",
        chevrolet: "images/logos/chevrolet.png",
    };
    return { ...car, logo: images[type] };
});